name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  name:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  secondName:
    description: 'test second param'
    required: true
    default: 'Everthing' 
  pathAction: "${{ github.workspace }}/test"
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}
    - ${{ inputs.secondName }}
