on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    container:
      image: dinkel/openldap
      env:
        SLAPD_PASSWORD: development
        SLAPD_DOMAIN: homie.dev
      ports:
        - 389:389
      options: --user root -v ${{ github.workspace }}/test:/etc/ldap.dist/prepopulate:rw
      
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          name: 'Virgilio'
          secondName: 'Padron'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
